### ISSUE TITLE
Visualization Editor: Request to Elasticsearch failed: "[Not Found] [type_missing_exception] type[[visualization]] missing

### ISSUE THREAD

**Issue by HandsomeWins** [sirensolutions/kibi#88] opened 2017-08-08 19:54 UTC
**Kibi version**: 5.4.0-beta-2

**Elasticsearch version**: v5.5.0

**Browser version**: Latest Chrome, Latest Firefox, both have same issue

**Original install method (e.g. download page, from source, etc.)**: Download Linux x64 version from the web download page, extract and modify Elasticsearch cluster settings the configuration YML file. 

**Description of the problem including expected versus actual behavior**: Can't save any visualizations due to Kibi proxy not translating the request properly. 

**Steps to reproduce**:
 1. Create a visualization.
 2. Try to save the visualization. 
 3. Same error message, every time. 

**Provide logs and/or server output (if relevant)**:

Visualization Editor: Request to Elasticsearch failed: "[Not Found] [type_missing_exception] type[[visualization]] missing, with { index_uuid=\"na\" & index=\"_all\" }"

Error: Request to Elasticsearch failed: "[Not Found] [type_missing_exception] type[[visualization]] missing, with { index_uuid=\"_na_\" & index=\"_all\" }"
    at http://localhost:5603/bundles/kibana.bundle.js?v=20715:26:17859
    at processQueue (http://localhost:5603/bundles/commons.bundle.js?v=20715:38:24400)
    at http://localhost:5603/bundles/commons.bundle.js?v=20715:38:24667
    at Scope.$eval (http://localhost:5603/bundles/commons.bundle.js?v=20715:39:5606)
    at Scope.$digest (http://localhost:5603/bundles/commons.bundle.js?v=20715:39:3420)
    at Scope.$apply (http://localhost:5603/bundles/commons.bundle.js?v=20715:39:6024)
    at done (http://localhost:5603/bundles/commons.bundle.js?v=20715:37:25748)
    at completeRequest (http://localhost:5603/bundles/commons.bundle.js?v=20715:37:29423)
    at XMLHttpRequest.xhr.onload (http://localhost:5603/bundles/commons.bundle.js?v=20715:37:30355)

Can you guys release a version that works for ELK 5.5? Or maybe just a hotfix to resolve this issue? Thanks.

**Comment by jccq** [comment] 2017-08-08 22:49
5.5 will be coming after 5.4.3 (which is not far at all), fastest thing is to use 5.4 at the moment.

**Comment by szydan** [comment] 2017-09-21 21:54
Duplicate of https://github.com/sirensolutions/kibi/issues/91
@HandsomeWins it will be fully addressed in 5.4.3-2 
You can build it today following the instruction in https://github.com/sirensolutions/kibi/issues/91

**Closed as completed by szydan** 2017-09-21 21:54 UTC
