### ISSUE TITLE
Kibi dies unexpectedly if connection (or ES) goes down

### ISSUE THREAD

**Issue by marfago** [sirensolutions/kibi#29] opened 2016-05-10 23:02 UTC
If ES is down or  unreacheable, kibi dies with:

/root/production/kibi/kibi-0.3.2-linux-x64/src/plugins/kibi_core/lib/query_engine.js:90
  self._isKibiIndexPresent().then(function () {
       ^
TypeError: undefined is not a function
    at [object Object].QueryEngine.loadTemplates [as _onTimeout](/root/production/kibi/kibi-0.3.2-linux-x64/src/plugins/kibi_core/lib/query_engine.js:90:8)
    at Timer.listOnTimeout (timers.js:119:15)

IMO, it should be a little more robust wrt ES availability.

**Comment by scampi** [comment] 2016-05-11 09:37
I cannot reproduce this with kibi 0.3.3 which should be release soon. Please retry again when that version is out.

**Comment by giorgio94c** [comment] 2016-05-20 10:49
Fixed in 4.4.1

**Closed as completed by giorgio94c** 2016-05-20 10:49 UTC
