### ISSUE TITLE
timeline

### ISSUE THREAD

**Issue by bertol83** [sirensolutions/kibi#18] opened 2016-03-15 15:08 UTC
In kibi 0.3 isn't possible to create a new timeline. The config (options) panel is disabled.

**Comment by scampi** [comment] 2016-03-15 22:40
I was able to create a new timeline in kibi 0.3.
Can you describe the steps you did to reach that state ?

**Comment by bertol83** [comment] 2016-03-16 08:10
Here the screenshot when i press on "Kibi Timeline" in visualize.
![image](https://cloud.githubusercontent.com/assets/13969336/13805654/c4b7d80e-eb56-11e5-9a7f-03697ad1da59.png)

**Comment by bertol83** [comment] 2016-03-16 08:14
In my opinion the problem is that the system doesn't ask me which search source start from.
I press "timeline" and there isn't the second step, but i go directly on the third (last) one.

**Comment by scampi** [comment] 2016-03-16 09:01
In the timeline, you can set more than one saved searches. This is why it is not proposed as it is for the other visualizations.
What version of the timeline do you have ? Is there any error in the logs (e.g., web inspector) ?

**Comment by bertol83** [comment] 2016-03-16 09:09
Version 0.3.0
Build   8511

the exception in the console is:

```
Error: [$compile:multidir] Multiple directives [kibiSelectPort (module: kibana), kibiSelectPort (module: kibana)] asking for new/isolated scope on: <div required="required" object-type="search" ng-model="group.savedSearchId">
http://errors.angularjs.org/1.4.7/$compile/multidir?p0=kibiSelectPort&p1=%20(module%3A%20kibana)&p2=kibiSelectPort&p3=%20(module%3A%20kibana)&p4=new%2Fisolated<vis-editor-vis-options vis="vis" class="ng-isolate-scope">cope&p5=%3Cdiv%20required%3D%22required%22%20object-type%3D%search%22%20ng-model%3D%22group.savedSearchId%22%3E
    at http://localhost:5606/bundles/commons.bundle.js?v=8511:27685:13
    at assertNoDuplicate (http://localhost:5606/bundles/commons.bundle.js?v=8511:36180:16)
    at applyDirectivesToNode (http://localhost:5606/bundles/commons.bundle.js?v=8511:35553:16)
    at compileNodes (http://localhost:5606/bundles/commons.bundle.js?v=8511:35215:16)
    at compileNodes (http://localhost:5606/bundles/commons.bundle.js?v=8511:35227:16)
    at compileNodes (http://localhost:5606/bundles/commons.bundle.js?v=8511:35227:16)
    at compileNodes (http://localhost:5606/bundles/commons.bundle.js?v=8511:35227:16)
    at compile (http://localhost:5606/bundles/commons.bundle.js?v=8511:35122:16)
    at applyDirectivesToNode (http://localhost:5606/bundles/commons.bundle.js?v=8511:35598:34)
    at compileNodes (http://localhost:5606/bundles/commons.bundle.js?v=8511:35215:16)commons.bundle.js?v=8511:40094 (anonymous function)commons.bundle.js?v=8511:36863 (anonymous function)commons.bundle.js?v=8511:36408 invokeLinkFncommons.bundle.js?v=8511:35906 nodeLinkFncommons.bundle.js?v=8511:35297 compositeLinkFncommons.bundle.js?v=8511:35901 nodeLinkFncommons.bundle.js?v=8511:35297 compositeLinkFncommons.bundle.js?v=8511:35901 nodeLinkFncommons.bundle.js?v=8511:35297 compositeLinkFncommons.bundle.js?v=8511:35301 compositeLinkFncommons.bundle.js?v=8511:35901 nodeLinkFncommons.bundle.js?v=8511:35297 compositeLinkFncommons.bundle.js?v=8511:35901 nodeLinkFncommons.bundle.js?v=8511:35297 compositeLinkFncommons.bundle.js?v=8511:35172 publicLinkFncommons.bundle.js?v=8511:35316 boundTranscludeFncommons.bundle.js?v=8511:35933 controllersBoundTranscludecommons.bundle.js?v=8511:51679 ngIfWatchActioncommons.bundle.js?v=8511:43443 Scope.$digestcommons.bundle.js?v=8511:43714 Scope.$applycommons.bundle.js?v=8511:39843 (anonymous function)commons.bundle.js?v=8511:22726 jQuery.event.dispatchcommons.bundle.js?v=8511:22412 elemData.handle
```

**Comment by scampi** [comment] 2016-03-21 09:32
I am not able to reproduce this error with kibi 0.3.2
Try with this newer version and tell me how this goes.

**Comment by scampi** [comment] 2016-04-07 08:57
Closing issue. Please reopen if you still have problems with this.

**Closed as completed by scampi** 2016-04-07 08:57 UTC
