### ISSUE TITLE
Kibi 5.2.2 Installation Error

### ISSUE THREAD

**Issue by shachar-ash** [sirensolutions/kibi#83] opened 2017-06-21 11:58 UTC
**Kibi version**: 5.2.2-beta-1

**Elasticsearch version**:5.3.2

**Server OS version**:Centos 7.3

**Original install method (e.g. download page, from source, etc.)**: Download the zip and install it with "kibana-plugin install"

**Description of the problem including expected versus actual behavior**: running the "kibana-plugin install" command fails with the following error:

Error: Cannot find module '/usr/share/kibana/plugins/.plugin.installing/kibana/kibi_radar_vis/package.json'
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"

**Steps to reproduce**:
 1. Download the zip (kibi-community-standalone-5.2.2-beta-1-linux-x64.zip)
 2. Run "kibana-plugin install file:///path/to/zip"

**Comment by szydan** [comment] 2017-07-27 10:44
Hi @madridista521 we've just released 5.4.0-beta-2
https://github.com/sirensolutions/kibi/releases/tag/tag-5.4.0-beta-2

If the version is not a problem could you try one more time on this version 
Mind that the command to install plugins changed to 
```
./bin/kibi-plugin install file:///path/to/zip
```
And that you will need the corresponding version of the plugin which should be  5.4.0-1
https://github.com/sirensolutions/kibi_radar_vis/releases/tag/5.4.0-1

**Comment by szydan** [comment] 2017-09-21 21:51
Closing, feel free to reopen if the issue is still there in Kibi > 5.4.0-beta-2

**Closed as completed by szydan** 2017-09-21 21:51 UTC
