### ISSUE TITLE
Issue about Dashboard search bar cookie.

### ISSUE THREAD

**Issue by sarufarr** [sirensolutions/kibi#55] opened 2016-08-30 08:01 UTC
### Versions

Kibi: 4.4.2-1

Operating System:
Server: CentOS 6.7
Client: Win10 Pro 1511
Browser：Chrome 52.0.2743.116 m
### Behavior

Use search bar and select cookie in the Dashboard.
#### Expected:

Use selected cookie as filter and refresh this Dashboard.
#### Actual:

Whole kibi page reloaded, and after reload action the whole page's dark theme did not work properly.
### Steps to reproduce the problem

1.Set kibi.yml: kibana.defaultAppId: dashborad/test
  Set kibi/Settings/Advanced: dashboard:defaultDarkTheme: true

2.Open kibi page in the browser

3.Type something(such as: "name:") in the search bar and select the cookie(such as: "name: sarufarr")

Then the whole page reloaded, and the dark theme seems crashed.

Forgive my laziness, there is another problem happened when I use kibi recently.
If I click the option button of the visualization window in Dashboard.
(Just the "Pen" beside the delete button "Close" on the left-top of the visualization window.)
The whole Dashboard page will change into white first and jumped into Visualize page.
And then if I click the Dashboard button to jump back to Dashboard page, I notice the visualization window shape changed. It seems that your dashboard layout adaptive algorithm goes wrong. After I refresh the whole page, the layout become correct again.

I'm sorry for my poor English. XD 
If you have some doubt about what I wrote, you can E-mail me.
Looking forward to receive your response.

**Comment by scampi** [comment] 2016-08-30 08:20
Can you try to reproduce this with the latest release 4.5.3 ?

**Comment by sarufarr** [comment] 2016-08-30 12:09
It does happen with the latest release 4.5.3 .

**Comment by szydan** [comment] 2016-08-30 13:35
@nvrdawn Thank you for verifying this

**Comment by scampi** [comment] 2016-08-30 16:16
I think you are experiencing something similar to https://github.com/elastic/kibana/issues/7801
I remember I had such a problem once, i.e., selecting the suggestion provoked a page reload. This is fixed in kibana 4.5.4, which will be our next release.

**Comment by sarufarr** [comment] 2016-08-31 07:56
Thx

**Comment by sarufarr** [comment] 2016-08-31 08:27
![searchbar](https://cloud.githubusercontent.com/assets/14183804/18121571/c6cc33f4-6f97-11e6-8cfb-5d8c22545e3e.gif)
Reproduce GIF

**Comment by scampi** [comment] 2017-03-22 11:02
fixed since 4.5.4

**Closed as completed by scampi** 2017-03-22 11:02 UTC
